logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: ALWAYS
  ignored:
  - "*.bundle.*"
  - favicon.ico
  user:
    password: password
spring:
  session:
    store-type: redis
  cloud:
    gateway:
      routes:
      - id: ui_route
        uri: http://localhost:8081
        predicates:
        - Path=/ui/
      - id: admin_route
        uri: http://localhost:8082
        predicates:
        - Path=/admin/
      - id: resource_route
        uri: http://localhost:9000
        predicates:
        - Path=/resource/ 
